### ISSUE TITLE
Add install step to Circle CI quick start guide

### ISSUE THREAD

**Issue by humphd** [threetreeslight/puppeteer-orb#2]
Thanks for https://circleci.com/orbs/registry/orb/threetreeslight/puppeteer, it's really been helpful.  One thing I struggled with, reading those docs, was not understanding that I needed to also call `puppeteer/install` in my steps.  Maybe this is so obvious you didn't think to include it, but a "Quick Start Guide" would be a great place to add it.

**Comment by thabti** [comment]
example:
```

version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          post:
            - git fetch --all
      - setup_remote_docker
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install --freeze-lockfile
      - puppeteer/install # <-------
      - run:
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
            then
                echo "Building production"
                yarn run build:prod
            else
                yarn run build
            fi
```
